spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.222.225.41:1002/user-info_db
    username: '{cipher}9ee72c41a3af42c553db80463b42a999108d3fb73b336a86b2453a26355f4245'
    password: '{cipher}20c8f92022778e0827f1514d2042e55afde235d80dc656cd70819016661e75c5'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://keycloak.trade-wise.store/auth/realms/go-selling-api
          jwk-set-uri: https://keycloak.trade-wise.store/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://8.222.225.41:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: https://keycloak.trade-wise.store/auth
  credentials:
    username: 'tradewise'
    password: 'tradewise321'
    client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
    secret: '{cipher}68cb6ac579e956cea85bc0dfedfb1bfa31fb186ac71e0913bdb8772ba29899585595c9b431f585262b85836a3c0e02637e2863c8db3fa0e4ac8011f7093263d4'
    provider: secret
file:
  uploadPath: user-info-service/src/main/resources/storage/
openapi:
  service:
    title: user-info-service
    version: 1.0.0
    # url: http://localhost:8080
    url: http://8.222.225.41:8080

springdoc:
  api-docs:
    path: /user-info-service/v3/api-docs
  swagger-ui:
    oauth:
      realm: 'go-selling-api'
      client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
      clientSecret: '{cipher}68cb6ac579e956cea85bc0dfedfb1bfa31fb186ac71e0913bdb8772ba29899585595c9b431f585262b85836a3c0e02637e2863c8db3fa0e4ac8011f7093263d4'
    path: /user-info-service/swagger-ui.html
