spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.222.225.41:1002/user-info_db
    username: '{cipher}9ee72c41a3af42c553db80463b42a999108d3fb73b336a86b2453a26355f4245'
    password: '{cipher}20c8f92022778e0827f1514d2042e55afde235d80dc656cd70819016661e75c5'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    eureka-server-u-r-l-defaultZone: http://eureka-server:8761/eureka/
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: http://localhost:1234/auth
  credentials:
    username: 'tradewise'
    password: 'tradewise321'
    client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
    secret: '{cipher}42d5f710c20655adbeeb9e9eb6d161d048664f4a9e749ede11e2cefa937299e79dc63978e0e88f6eb32a730d84c50413514e4df55f056586a6813b2b647d445a'
    provider: secret
file:
  uploadPath: user-info-service/src/main/resources/storage/
openapi:
  service:
    title: user-info-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /user-info-service/v3/api-docs
  swagger-ui:
    oauth:
      realm: 'go-selling-api'
      client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
      clientSecret: '{cipher}42d5f710c20655adbeeb9e9eb6d161d048664f4a9e749ede11e2cefa937299e79dc63978e0e88f6eb32a730d84c50413514e4df55f056586a6813b2b647d445a'
    path: /user-info-service/swagger-ui.html
